import { StyleSheet, Platform } from 'react-native';
import { lightColors } from '../../constants/colors';

export const createTasksStyles = (colors: typeof lightColors) => StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
  },
  center: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  header: {
    backgroundColor: colors.card,
    padding: 24,
    paddingTop: Platform.OS === 'ios' ? 60 : 45,
    borderBottomWidth: 0,
    shadowColor: colors.shadow,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 16,
    elevation: 8,
    position: 'relative',
    zIndex: 10, // Ensure header sits above content
  },
  headerGradient: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    height: '50%',
    opacity: 0.08,
  },
  headerTop: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
    position: 'relative',
  },
  backButton: {
    padding: 10,
    borderRadius: 12,
    backgroundColor: colors.primary + '15',
  },
  backButtonText: {
    fontSize: 20,
    color: colors.primary,
    fontWeight: '800',
  },
  title: {
    fontSize: 32,
    fontWeight: '900',
    color: colors.primary,
    letterSpacing: -1,
    lineHeight: 38, // Ensure sufficient height for the font
    textAlign: 'center',
  },
  headerActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  iconButton: {
    padding: 10,
    borderRadius: 12,
    backgroundColor: colors.primary + '15',
  },
  taskCount: {
    fontSize: 15,
    color: colors.textSecondary,
    fontWeight: '600',
    marginTop: 0,
  },
  searchSortRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    width: '100%',
    marginBottom: 16,
  },
  searchInput: {
    flex: 1,
    borderWidth: 2,
    borderColor: colors.border,
    borderRadius: 16,
    padding: 14,
    fontSize: 16,
    backgroundColor: colors.surface,
    color: colors.text,
    fontWeight: '500',
  },
  sortButton: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 10,
    paddingHorizontal: 16,
    backgroundColor: colors.surface,
    borderRadius: 12,
    alignSelf: 'flex-start',
    borderWidth: 1.5,
    borderColor: colors.border,
    shadowColor: colors.shadow,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
  },
  sortButtonText: {
    fontSize: 14,
    color: colors.primary,
    fontWeight: '700',
    marginLeft: 6,
  },
  sortMenuOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.4)',
    justifyContent: 'flex-end',
    zIndex: 1000,
  },
  sortMenuContent: {
    backgroundColor: colors.card,
    borderTopLeftRadius: 32,
    borderTopRightRadius: 32,
    padding: 24,
    paddingBottom: Platform.OS === 'ios' ? 40 : 24,
  },
  sortMenuTitle: {
    fontSize: 24,
    fontWeight: '900',
    marginBottom: 20,
    color: colors.text,
    letterSpacing: -0.5,
  },
  sortOption: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 16,
    paddingHorizontal: 20,
    borderRadius: 16,
    marginBottom: 10,
    backgroundColor: colors.surface,
    borderWidth: 1.5,
    borderColor: colors.border,
  },
  sortOptionSelected: {
    backgroundColor: colors.primary,
    borderColor: colors.primary,
  },
  sortOptionText: {
    fontSize: 17,
    color: colors.text,
    fontWeight: '600',
  },
  sortOptionTextSelected: {
    color: '#fff',
    fontWeight: '800',
  },
  taskItem: {
    backgroundColor: colors.card,
    padding: 20,
    marginHorizontal: 16,
    marginVertical: 8,
    borderRadius: 20,
    shadowColor: colors.shadow,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 12,
    elevation: 5,
    borderWidth: 1.5,
    borderColor: colors.border,
  },
  taskItemCompleted: {
    opacity: 0.7,
    backgroundColor: colors.surface,
  },
  taskItemOverdue: {
    borderColor: colors.error + '40',
  },
  taskContent: {
    flexDirection: 'row',
    alignItems: 'flex-start',
  },
  taskCheckbox: {
    width: 26,
    height: 26,
    borderRadius: 8,
    borderWidth: 2.5,
    borderColor: colors.primary,
    marginRight: 16,
    marginTop: 2,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: colors.surface,
  },
  taskCheckboxCompleted: {
    backgroundColor: colors.primary,
    borderColor: colors.primary,
  },
  checkmark: {
    color: '#fff',
    fontSize: 18,
    fontWeight: '900',
  },
  taskTextContainer: {
    flex: 1,
  },
  taskText: {
    fontSize: 17,
    color: colors.text,
    fontWeight: '700',
    lineHeight: 24,
    letterSpacing: -0.3,
  },
  taskTextCompleted: {
    textDecorationLine: 'line-through',
    color: colors.textSecondary,
    fontWeight: '500',
  },
  taskMetaRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignItems: 'center',
    gap: 10,
    marginTop: 8,
  },
  metaItem: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.border,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 8,
  },
  dueDate: {
    fontSize: 13,
    color: colors.textSecondary,
    fontWeight: '600',
  },
  dueDateOverdue: {
    color: colors.error,
    fontWeight: '700',
  },
  completionCount: {
    fontSize: 12,
    color: colors.success,
    fontWeight: '800',
    backgroundColor: colors.success + '15',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 10,
    overflow: 'hidden',
  },
  listContentContainer: {
    paddingTop: 8,
    paddingBottom: Platform.OS === 'ios' ? 120 : 100,
  },
  emptyContainer: {
    flexGrow: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: 100,
  },
  emptyIcon: {
    fontSize: 72,
    marginBottom: 20,
    opacity: 0.4,
  },
  emptyText: {
    fontSize: 22,
    color: colors.text,
    fontWeight: '800',
    marginBottom: 8,
    letterSpacing: -0.5,
  },
  emptySubtext: {
    fontSize: 15,
    color: colors.textSecondary,
    textAlign: 'center',
    paddingHorizontal: 60,
    lineHeight: 22,
    opacity: 0.7,
  },
  fab: {
    position: 'absolute',
    right: 24,
    bottom: Platform.OS === 'ios' ? 50 : 60,
    width: 68,
    height: 68,
    borderRadius: 24,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: colors.primary,
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.4,
    shadowRadius: 16,
    elevation: 12,
    borderWidth: 2,
    borderColor: 'rgba(255, 255, 255, 0.4)',
    zIndex: 999, // Ensure FAB is above all content
  },
  fabText: {
    fontSize: 38,
    color: '#fff',
    fontWeight: '300',
    lineHeight: 38,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'transparent', // Transparent to let BlurView work
    justifyContent: 'flex-end',
  },
  modalContent: {
    backgroundColor: colors.card,
    borderTopLeftRadius: 36,
    borderTopRightRadius: 36,
    width: '100%',
    padding: 0,
    paddingBottom: Platform.OS === 'ios' ? 44 : 28,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: -10 },
    shadowOpacity: 0.2,
    shadowRadius: 20,
    elevation: 25,
  },
  modalScrollView: {
    maxHeight: 500,
  },
  modalScrollContent: {
    padding: 24,
  },
  modalTitle: {
    fontSize: 28,
    fontWeight: '900',
    padding: 28,
    paddingBottom: 20,
    color: colors.text,
    letterSpacing: -0.5,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
    backgroundColor: colors.surface,
  },
  input: {
    borderWidth: 2,
    borderColor: colors.border,
    borderRadius: 18,
    padding: 18,
    fontSize: 17,
    marginBottom: 20,
    backgroundColor: colors.surface,
    minHeight: 60,
    color: colors.text,
    fontWeight: '500',
  },
  modalButtons: {
    flexDirection: 'row',
    gap: 12,
    paddingHorizontal: 24,
    marginTop: 12,
  },
  modalButton: {
    flex: 1,
    paddingVertical: 18,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 60,
  },
  cancelButton: {
    backgroundColor: colors.surface,
    borderWidth: 2,
    borderColor: colors.border,
  },
  cancelButtonText: {
    color: colors.textSecondary,
    fontSize: 17,
    fontWeight: '700',
  },
  submitButton: {
    backgroundColor: colors.primary,
    shadowColor: colors.primary,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.4,
    shadowRadius: 16,
    elevation: 10,
  },
  submitButtonText: {
    color: '#fff',
    fontSize: 17,
    fontWeight: '800',
  },
});
