import { StyleSheet, Platform } from 'react-native';
import { lightColors } from '../../constants/colors';

export const createTaskDetailsStyles = (colors: typeof lightColors) =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: colors.surface,
    },
    screenHeader: {
      backgroundColor: colors.card,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      padding: 24,
      paddingTop: Platform.OS === 'ios' ? 60 : 45,
      paddingBottom: 24,
      borderBottomWidth: 0,
      shadowColor: colors.shadow,
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.15,
      shadowRadius: 16,
      elevation: 8,
      position: 'relative',
      overflow: 'hidden',
    },
    headerGradient: {
      position: 'absolute',
      top: 0,
      left: 0,
      right: 0,
      height: '100%',
      opacity: 0.1,
    },
    backButton: {
      padding: 12,
      borderRadius: 14,
      backgroundColor: colors.primary + '15',
    },
    backButtonText: {
      fontSize: 17,
      color: colors.primary,
      fontWeight: '800',
      letterSpacing: 0.2,
    },
    // New premium icon styles
    iconContainer: {
      width: 44,
      height: 44,
      borderRadius: 12,
      backgroundColor: colors.primary + '10',
      justifyContent: 'center',
      alignItems: 'center',
      marginRight: 16,
    },
    sectionIconRow: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: 16,
    },
    badge: {
      paddingHorizontal: 8,
      paddingVertical: 4,
      borderRadius: 8,
      backgroundColor: colors.primary + '15',
      marginLeft: 8,
    },
    badgeText: {
      fontSize: 12,
      fontWeight: '700',
      color: colors.primary,
      textTransform: 'uppercase',
    },
    screenTitle: {
      fontSize: 28,
      fontWeight: '900',
      color: colors.primary,
      letterSpacing: -0.8,
      textShadowColor: colors.primary + '33',
      textShadowOffset: { width: 0, height: 2 },
      textShadowRadius: 4,
    },
    headerSpacer: {
      width: 60,
    },
    center: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: colors.surface,
    },
    scrollView: {
      flex: 1,
    },
    scrollContent: {
      padding: 20,
      paddingBottom: Platform.OS === 'ios' ? 80 : 60,
    },
    header: {
      backgroundColor: colors.card,
      borderRadius: 24,
      padding: 24,
      marginBottom: 20,
      shadowColor: colors.primary,
      shadowOffset: { width: 0, height: 6 },
      shadowOpacity: 0.12,
      shadowRadius: 16,
      elevation: 8,
      borderWidth: 1.5,
      borderColor: colors.border,
    },
    headerTop: {
      flexDirection: 'row',
      alignItems: 'center',
    },
    checkbox: {
      width: 28,
      height: 28,
      borderRadius: 14,
      borderWidth: 2.5,
      borderColor: colors.primary,
      marginRight: 14,
      justifyContent: 'center',
      alignItems: 'center',
    },
    checkboxCompleted: {
      backgroundColor: colors.primary,
    },
    checkmark: {
      color: '#fff',
      fontSize: 18,
      fontWeight: 'bold',
    },
    headerText: {
      flex: 1,
    },
    title: {
      fontSize: 26,
      fontWeight: '800',
      color: colors.text,
      letterSpacing: -0.4,
    },
    titleCompleted: {
      textDecorationLine: 'line-through',
      color: colors.textSecondary,
    },
    completionCountBadge: {
      fontSize: 13,
      color: colors.success,
      fontWeight: '700',
      backgroundColor: colors.success + '20',
      paddingHorizontal: 12,
      paddingVertical: 6,
      borderRadius: 14,
      marginTop: 12,
      alignSelf: 'flex-start',
      overflow: 'hidden',
    },
    editButton: {
      marginTop: 18,
      paddingVertical: 14,
      paddingHorizontal: 24,
      backgroundColor: colors.primary,
      borderRadius: 16,
      alignSelf: 'flex-start',
      shadowColor: colors.primary,
      shadowOffset: { width: 0, height: 6 },
      shadowOpacity: 0.4,
      shadowRadius: 12,
      elevation: 8,
    },
    headerEditButton: {
      padding: 10,
      borderRadius: 14,
      backgroundColor: colors.primary + '15',
      marginLeft: 12,
      alignSelf: 'flex-start', // Align with top of title
      marginTop: 4,
    },
    editButtonText: {
      color: '#fff',
      fontSize: 16,
      fontWeight: '700',
      letterSpacing: 0.3,
    },
    editInput: {
      fontSize: 24,
      fontWeight: '800',
      color: colors.text,
      borderBottomWidth: 2.5,
      borderBottomColor: colors.primary,
      paddingBottom: 10,
      paddingTop: 6,
      letterSpacing: -0.3,
    },
    section: {
      backgroundColor: colors.card,
      borderRadius: 24,
      padding: 24,
      marginBottom: 20,
      shadowColor: colors.shadow,
      shadowOffset: { width: 0, height: 6 },
      shadowOpacity: 0.1,
      shadowRadius: 12,
      elevation: 4,
      borderWidth: 1,
      borderColor: colors.border,
    },
    sectionHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: 16,
    },
    sectionTitle: {
      fontSize: 20,
      fontWeight: '800',
      color: colors.text,
      letterSpacing: -0.5,
    },
    progressText: {
      fontSize: 15,
      color: colors.textSecondary,
      fontWeight: '600',
    },
    progressBar: {
      height: 10,
      backgroundColor: colors.border,
      borderRadius: 5,
      marginBottom: 18,
      overflow: 'hidden',
    },
    progressFill: {
      height: '100%',
      backgroundColor: colors.primary,
      borderRadius: 5,
    },
    infoRow: {
      flexDirection: 'column',
      marginBottom: 16,
    },
    infoLabel: {
      fontSize: 13,
      fontWeight: '800',
      color: colors.textSecondary,
      textTransform: 'uppercase',
      letterSpacing: 0.8,
      marginBottom: 6,
    },
    infoValue: {
      fontSize: 17,
      color: colors.text,
      fontWeight: '600',
      // Removed bulky box styling for cleaner look
      marginTop: 2,
      paddingVertical: 4,
    },
    datePickerContainer: {
      flex: 1,
    },
    stepItem: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingVertical: 14,
      borderBottomWidth: 1,
      borderBottomColor: colors.border,
    },
    stepItemCompleted: {
      opacity: 0.6,
    },
    stepCheckbox: {
      width: 22,
      height: 22,
      borderRadius: 11,
      borderWidth: 2.5,
      borderColor: colors.primary,
      marginRight: 14,
      justifyContent: 'center',
      alignItems: 'center',
    },
    stepContent: {
      flex: 1,
    },
    stepText: {
      fontSize: 17,
      color: colors.text,
      fontWeight: '500',
    },
    stepTextCompleted: {
      textDecorationLine: 'line-through',
      color: colors.textSecondary,
    },
    stepActions: {
      flexDirection: 'row',
      alignItems: 'center',
      marginLeft: 8,
      gap: 8,
    },
    stepEditButton: {
      padding: 8,
    },
    stepEditButtonText: {
      fontSize: 18,
    },
    stepDeleteButton: {
      padding: 8,
    },
    stepDeleteButtonText: {
      fontSize: 18,
    },
    stepEditContainer: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
      marginLeft: 8,
    },
    stepEditInput: {
      flex: 1,
      fontSize: 17,
      color: colors.text,
      borderWidth: 2,
      borderColor: colors.primary,
      borderRadius: 12,
      padding: 12,
      marginRight: 10,
      backgroundColor: colors.surface,
    },
    stepEditSaveButton: {
      width: 36,
      height: 36,
      borderRadius: 18,
      backgroundColor: colors.success,
      justifyContent: 'center',
      alignItems: 'center',
      marginRight: 8,
      shadowColor: colors.success,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.3,
      shadowRadius: 4,
      elevation: 4,
    },
    stepEditSaveText: {
      color: '#fff',
      fontSize: 18,
      fontWeight: 'bold',
    },
    stepEditCancelButton: {
      width: 36,
      height: 36,
      borderRadius: 18,
      backgroundColor: colors.error,
      justifyContent: 'center',
      alignItems: 'center',
      shadowColor: colors.error,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.3,
      shadowRadius: 4,
      elevation: 4,
    },
    stepEditCancelText: {
      color: '#fff',
      fontSize: 16,
      fontWeight: 'bold',
    },
    emptyText: {
      fontSize: 15,
      color: colors.textSecondary,
      fontStyle: 'italic',
      textAlign: 'center',
      paddingVertical: 24,
    },
    emptyStepsContainer: {
      paddingVertical: 32,
      alignItems: 'center',
    },
    emptyStepsIcon: {
      fontSize: 56,
      marginBottom: 16,
      opacity: 0.2,
      color: colors.textSecondary,
    },
    emptyStepsText: {
      fontSize: 18,
      color: colors.textSecondary,
      fontWeight: '700',
      marginBottom: 8,
    },
    emptyStepsSubtext: {
      fontSize: 15,
      color: colors.textSecondary,
      textAlign: 'center',
      opacity: 0.6,
      lineHeight: 20,
    },
    addStepButton: {
      marginTop: 20,
      paddingVertical: 16,
      paddingHorizontal: 20,
      backgroundColor: colors.surface,
      borderRadius: 16,
      alignItems: 'center',
      borderWidth: 2,
      borderColor: colors.primary,
      borderStyle: 'dashed',
    },
    addStepButtonText: {
      color: colors.primary,
      fontSize: 16,
      fontWeight: '800',
      letterSpacing: 0.5,
    },
    editActions: {
      flexDirection: 'row',
      gap: 12,
      marginTop: 24,
    },
    actionButton: {
      flex: 1,
      paddingVertical: 18,
      borderRadius: 18,
      alignItems: 'center',
      justifyContent: 'center',
      minHeight: 60,
    },
    cancelButton: {
      backgroundColor: colors.surface,
      borderWidth: 2.5,
      borderColor: colors.border,
    },
    cancelButtonText: {
      color: colors.textSecondary,
      fontSize: 17,
      fontWeight: '800',
      letterSpacing: 0.5,
    },
    saveButton: {
      backgroundColor: colors.primary,
      shadowColor: colors.primary,
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.4,
      shadowRadius: 16,
      elevation: 10,
    },
    saveButtonText: {
      color: '#fff',
      fontSize: 17,
      fontWeight: '900',
      letterSpacing: 0.5,
    },
    modalOverlay: {
      flex: 1,
      backgroundColor: 'rgba(0, 0, 0, 0.7)',
      justifyContent: 'flex-end',
    },
    modalContent: {
      backgroundColor: colors.card,
      borderTopLeftRadius: 36,
      borderTopRightRadius: 36,
      padding: 0,
      paddingBottom: Platform.OS === 'ios' ? 44 : 28,
      maxHeight: '85%',
      flex: 1,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: -12 },
      shadowOpacity: 0.3,
      shadowRadius: 24,
      elevation: 25,
      overflow: 'hidden',
    },
    modalTitle: {
      fontSize: 28,
      fontWeight: '900',
      padding: 28,
      paddingBottom: 24,
      color: colors.text,
      letterSpacing: -0.5,
      backgroundColor: colors.surface,
      borderBottomWidth: 1,
      borderBottomColor: colors.border,
    },
    input: {
      borderWidth: 2,
      borderColor: colors.border,
      borderRadius: 18,
      padding: 20,
      fontSize: 17,
      marginHorizontal: 24,
      marginTop: 24,
      marginBottom: 24,
      backgroundColor: colors.surface,
      minHeight: 60,
      color: colors.text,
      fontWeight: '600',
    },
    modalButtons: {
      flexDirection: 'row',
      gap: 12,
      paddingHorizontal: 24,
    },
    modalButton: {
      flex: 1,
      paddingVertical: 18,
      borderRadius: 18,
      alignItems: 'center',
      justifyContent: 'center',
      minHeight: 60,
    },
    submitButton: {
      backgroundColor: colors.primary,
      shadowColor: colors.primary,
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.4,
      shadowRadius: 16,
      elevation: 10,
    },
    submitButtonText: {
      color: '#fff',
      fontSize: 17,
      fontWeight: '900',
    },
    errorText: {
      fontSize: 17,
      color: colors.error,
      fontWeight: '600',
    },
    remindersList: {
      flex: 1,
      marginTop: 8,
    },
    reminderDisplayItem: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: 12,
      backgroundColor: colors.surface,
      padding: 16,
      borderRadius: 16,
      borderWidth: 1,
      borderColor: colors.border,
    },
    reminderDisplayText: {
      fontSize: 15,
      color: colors.text,
      fontWeight: '600',
      flex: 1,
    },
    alarmToggleButton: {
      flexDirection: 'row',
      alignItems: 'center',
      padding: 10,
      paddingHorizontal: 16,
      marginLeft: 12,
      borderRadius: 12,
      backgroundColor: colors.border,
      minWidth: 85,
      justifyContent: 'center',
    },
    alarmToggleButtonActive: {
      backgroundColor: colors.primary + '20',
    },
    alarmToggleIcon: {
      fontSize: 18,
      marginRight: 6,
      color: colors.textSecondary,
    },
    alarmToggleIconActive: {
      color: colors.primary,
    },
    alarmToggleText: {
      fontSize: 12,
      fontWeight: '800',
      color: colors.textSecondary,
    },
    alarmToggleTextActive: {
      color: colors.primary,
      fontWeight: '800',
    },
    // Add missing styles for ReminderConfig
    addButton: {
      paddingHorizontal: 16,
      paddingVertical: 10,
      backgroundColor: colors.primary,
      borderRadius: 12,
      shadowColor: colors.primary,
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.3,
      shadowRadius: 8,
      elevation: 4,
    },
    addButtonText: {
      color: '#fff',
      fontSize: 14,
      fontWeight: '800',
    },
    reminderItem: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      backgroundColor: colors.card,
      padding: 16,
      borderRadius: 16,
      marginBottom: 12,
      borderWidth: 1,
      borderColor: colors.border,
    },
    reminderContent: {
      flex: 1,
    },
    reminderTextRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
    },
    reminderText: {
      fontSize: 16,
      color: colors.text,
      fontWeight: '600',
      flex: 1,
    },
    alarmToggle: {
      padding: 10,
      borderRadius: 12,
      backgroundColor: colors.border,
    },
    alarmToggleActive: {
      backgroundColor: colors.primary + '20',
    },
    alarmIndicator: {
      fontSize: 18,
    },
    reminderActions: {
      flexDirection: 'row',
      gap: 10,
      marginLeft: 10,
    },
    deleteButton: {
      width: 36,
      height: 36,
      borderRadius: 18,
      backgroundColor: colors.error + '15',
      justifyContent: 'center',
      alignItems: 'center',
    },
    deleteButtonText: {
      color: colors.error,
      fontSize: 20,
      fontWeight: '800',
    },
    editorContent: {
      flex: 1,
    },
    editorContentContainer: {
      padding: 24,
    },
    label: {
      fontSize: 14,
      fontWeight: '800',
      color: colors.textSecondary,
      textTransform: 'uppercase',
      letterSpacing: 0.8,
      marginTop: 20,
      marginBottom: 12,
    },
    optionsGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 10,
      marginBottom: 8,
    },
    optionButton: {
      paddingHorizontal: 16,
      paddingVertical: 12,
      borderRadius: 14,
      borderWidth: 2,
      borderColor: colors.border,
      backgroundColor: colors.surface,
      minWidth: 100,
      justifyContent: 'center',
      alignItems: 'center',
    },
    optionButtonSelected: {
      backgroundColor: colors.primary,
      borderColor: colors.primary,
    },
    optionText: {
      fontSize: 14,
      color: colors.textSecondary,
      fontWeight: '700',
    },
    optionTextSelected: {
      color: '#fff',
    },
    helperText: {
      fontSize: 13,
      color: colors.textSecondary,
      marginTop: -8,
      marginBottom: 12,
      opacity: 0.7,
    },
    dragHandle: {
      width: 40,
      height: 5,
      backgroundColor: colors.border,
      borderRadius: 3,
      alignSelf: 'center',
      marginTop: 12,
    },
    modalHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      padding: 24,
      paddingBottom: 16,
      borderBottomWidth: 1,
      borderBottomColor: colors.border,
    },
    closeButton: {
      width: 36,
      height: 36,
      borderRadius: 18,
      backgroundColor: colors.border,
      justifyContent: 'center',
      alignItems: 'center',
    },
    closeButtonText: {
      fontSize: 18,
      color: colors.textSecondary,
      fontWeight: '800',
    },
    infoBox: {
      backgroundColor: colors.primary + '10',
      padding: 16,
      borderRadius: 16,
      marginTop: 12,
      marginBottom: 12,
      borderWidth: 1,
      borderColor: colors.primary + '20',
    },
    infoText: {
      fontSize: 14,
      color: colors.primary,
      lineHeight: 20,
      fontWeight: '600',
    },
    alarmOption: {
      marginTop: 20,
      padding: 16,
      backgroundColor: colors.surface,
      borderRadius: 16,
      borderWidth: 1,
      borderColor: colors.border,
    },
    alarmToggleOption: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingVertical: 8,
    },
    toggleSwitch: {
      width: 54,
      height: 30,
      borderRadius: 15,
      backgroundColor: colors.border,
      padding: 2,
    },
    toggleSwitchActive: {
      backgroundColor: colors.success,
    },
    toggleThumb: {
      width: 26,
      height: 26,
      borderRadius: 13,
      backgroundColor: '#fff',
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.2,
      shadowRadius: 4,
      elevation: 2,
    },
    alarmLabel: {
      fontSize: 16,
      color: colors.text,
      fontWeight: '700',
    },
  });
